name: phyling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aster>=1.19
  - fasttree>=2.1.1
  - iqtree>=2.4.0,<3.0
  - muscle>=5.3
  - python>=3.9,<3.14
  - raxml-ng>=1.2.2
  - samtools>=1.21
  - pip
  - pip:
    - -e .[dev]
